config:
  blocks:
    solo: SPONGE
    group: GOLD_BLOCK
    plate: IRON_PLATE
    button: STONE_BUTTON
  coordinates:
    minX: 100
    minZ: 100
    maxX: 100
    maxZ: 100
  messages:
    teleport: "Przeteleportowano w losowe koordy"
    emptyList: "W okolicy nie ma przeciwnika dla Ciebie"
